### ISSUE TITLE
Add smatch to PyPI

### ISSUE THREAD

**Issue by mpertierra** [snowblink14/smatch#5]
@snowblink14

**Comment by nschneid** [comment]
And/or NLTK?

**Comment by mpertierra** [comment]
@nschneid What do you mean? NLTK is already in PyPI (https://pypi.python.org/pypi/nltk). Also, NLTK is not a dependency of smatch.

**Comment by nschneid** [comment]
I meant that perhaps smatch should be added to NLTK.

**Comment by mpertierra** [comment]
@nschneid oh I see, that would be nice. I don't know how likely it is that it would be accepted, as this would be the first AMR-related module in NLTK.

**Comment by nschneid** [comment]
Having contributed modules to NLTK, I think they would be open to well-designed and well-documented AMR functionality. It would take some work to adapt the current smatch code, e.g., to make it compatible with Python 3.x as well as 2.7.

**Comment by nschneid** [comment]
I have considered contributing my [API for reading AMRs](https://github.com/nschneid/amr-hackathon/tree/master/src) to NLTK, but haven't had the time to make it happen. It might also make sense to reimplement smatch using this API, if someone wants to volunteer. :)

**Comment by mpertierra** [comment]
@nschneid That sounds like a good idea. By the way, have you tried using [penman](https://github.com/goodmami/penman) ?

**Comment by nschneid** [comment]
Haven't used it—my understanding is there is some overlap in functionality between the two APIs, but there are also some things that each supports but the other doesn't. Might be worth incorporating elements of both into NLTK.

**Comment by snowblink14** [comment]
Looks like we have 3 requests:
1) Add smatch to PyPI/NLTK
2) Make the code Python 3.x compatible
3) Reimplement smatch using @nschneid's AMR reading API

All should be nice improvements. I'll see what I can do and help is always welcome.

**Comment by mpertierra** [comment]
@snowblink14 This is a good tutorial to adding a package to PyPI (http://peterdowns.com/posts/first-time-with-pypi.html).

**Comment by danielhers** [comment]
@snowblink14 I think (1) is the highest priority. I think most people using Python today much prefer installing packages with pip rather than having to clone a github repository.

**Comment by snowblink14** [comment]
@danielhers Thanks for uploading smatch to PyPI and making the setup.py! My PyPI username is shucai. Can you add me to the project? And I'll merge setup.py soon.
