### ISSUE TITLE
Nondeterministic Behavior

### ISSUE THREAD

**Issue by jsteffen** [snowblink14/smatch#8]
I noticed that the smatch tool sometimes produces different results on the same input. Is this a known behavior? 
Here is a simple example. I have the follwing two AMRs:

`gold.amr`
```
(v1 / res
  :tar (v2 / rere
    :rest (v3 / rest
      :pay (v4 / cc
        :na "cname1"))
    :prt (v5 / and
      :op1 (v6 / per
        :qua "num1")
      :op2 (v7 / chi
        :qua "num2"))))
```
`pred.amr`
```
(v1 / se
  :tar (v2 / rest
    :ham (v3 / and
      :op1 (v4 / mq
        :qua "num1")
      :op2 (v5 / per
        :qua "num1"))))
```
I'm running the smatch tool like this:
`./smatch.py -f gold.amr pred.amr --pr`
Most of the time, the result is this:
```
Precision: 0.29
Recall: 0.42
F-score: 0.34
```
But from time to time, I also get this result:
```
Precision: 0.24
Recall: 0.33
F-score: 0.28
```

**Comment by snowblink14** [comment]
@jsteffen Smatch can be nondeterministic because it uses heuristic search method to compute the optimal maximum f-score. The problem of finding optimal variable alignment between two AMRs is NP-complete. More analysis and proof is in the [paper](https://amr.isi.edu/smatch-13.pdf).
